lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(JWT_TOKEN_TTL)%'
    private_key_path: '%kernel.project_dir%/jwt/private.pem'
    public_key_path:  '%kernel.project_dir%/jwt/public.pem'
